language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_0b980ef632b8_key -iv $encrypted_0b980ef632b8_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 47.95.235.183\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
addons:
  ssh_known_hosts: 47.95.235.183
after_success:
- ssh root@47.95.235.183 'cd /home/testci && git clone https://github.com/BestDingSheng/dingsheng-cli.git'